#!/bin/zsh

export STOW_FOLDERS="personal,git,tmux,bin,nvim,alfred,ghostty"

pushd $HOME/.dotfiles
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow --verbose --restow $folder
done
popd
