#!/bin/zsh

export STOW_FOLDERS="zsh,work,git,tmux,readline,bin,nvim,fzf,alfred,alacritty,ghostty"

pushd $HOME/.dotfiles
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow --verbose --restow $folder
done
popd
