#!/bin/zsh

export STOW_FOLDERS="zsh,personal,git,tmux,readline,bin,nvim,fzf,alfred"

pushd $HOME/.dotfiles
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow --verbose --restow $folder
done
popd
