#!/usr/bin/bash

export STOW_FOLDERS="omarchy/alacritty,nvim,hyperland,bash"

pushd $HOME/.dotfiles
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow --verbose --restow $folder
done
popd
