#!/bin/sh

# Add a directory to PATH if not already present
addToPath() {
  if [[ "$PATH" != *"$1"* ]]; then
    export PATH=$PATH:$1
  fi
}

# Source a file only if it exists
source_if_exists() {
  if [ -f $1 ]; then
    source $1
  fi
}
